
package pizzatech.dbaccess.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.6
 * Thu May 03 15:31:41 EEST 2012
 * Generated source version: 2.4.6
 */

@XmlRootElement(name = "getAllMainIngedients", namespace = "http://pizzatech")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getAllMainIngedients", namespace = "http://pizzatech")

public class GetAllMainIngedients {


}

