
package client.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.6
 * Sat Apr 21 18:52:37 EEST 2012
 * Generated source version: 2.4.6
 */

@XmlRootElement(name = "addPizzaResponse", namespace = "http://client/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addPizzaResponse", namespace = "http://client/")

public class AddPizzaResponse {


}

