
package client.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.6
 * Sat Apr 21 18:52:37 EEST 2012
 * Generated source version: 2.4.6
 */

@XmlRootElement(name = "getPizzaById", namespace = "http://client/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getPizzaById", namespace = "http://client/")

public class GetPizzaById {

    @XmlElement(name = "arg0")
    private int arg0;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

}

