
package pizzatech.dbaccess.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.6
 * Sat May 12 17:11:34 EEST 2012
 * Generated source version: 2.4.6
 */

@XmlRootElement(name = "getAllOrders", namespace = "http://pizzatech")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getAllOrders", namespace = "http://pizzatech")

public class GetAllOrders {

    @XmlElement(name = "arg0")
    private int arg0;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

}

