package pizzatech.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2012-05-03T10:14:18.043+03:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://pizzatech", name = "PizzaTechService")
@XmlSeeAlso({ObjectFactory.class})
public interface PizzaTechService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllOrders", targetNamespace = "http://pizzatech", className = "pizzatech.test.GetAllOrders")
    @WebMethod
    @ResponseWrapper(localName = "getAllOrdersResponse", targetNamespace = "http://pizzatech", className = "pizzatech.test.GetAllOrdersResponse")
    public java.util.List<pizzatech.test.Order> getAllOrders();

    @RequestWrapper(localName = "addPizza", targetNamespace = "http://pizzatech", className = "pizzatech.test.AddPizza")
    @WebMethod
    @ResponseWrapper(localName = "addPizzaResponse", targetNamespace = "http://pizzatech", className = "pizzatech.test.AddPizzaResponse")
    public void addPizza(
        @WebParam(name = "arg0", targetNamespace = "")
        pizzatech.test.Pizza arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllPizzas", targetNamespace = "http://pizzatech", className = "pizzatech.test.GetAllPizzas")
    @WebMethod
    @ResponseWrapper(localName = "getAllPizzasResponse", targetNamespace = "http://pizzatech", className = "pizzatech.test.GetAllPizzasResponse")
    public java.util.List<pizzatech.test.Pizza> getAllPizzas();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllMainIngedients", targetNamespace = "http://pizzatech", className = "pizzatech.test.GetAllMainIngedients")
    @WebMethod
    @ResponseWrapper(localName = "getAllMainIngedientsResponse", targetNamespace = "http://pizzatech", className = "pizzatech.test.GetAllMainIngedientsResponse")
    public java.util.List<pizzatech.test.Ingredient> getAllMainIngedients();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllDoughTypes", targetNamespace = "http://pizzatech", className = "pizzatech.test.GetAllDoughTypes")
    @WebMethod
    @ResponseWrapper(localName = "getAllDoughTypesResponse", targetNamespace = "http://pizzatech", className = "pizzatech.test.GetAllDoughTypesResponse")
    public java.util.List<pizzatech.test.Ingredient> getAllDoughTypes();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllToppings", targetNamespace = "http://pizzatech", className = "pizzatech.test.GetAllToppings")
    @WebMethod
    @ResponseWrapper(localName = "getAllToppingsResponse", targetNamespace = "http://pizzatech", className = "pizzatech.test.GetAllToppingsResponse")
    public java.util.List<pizzatech.test.Ingredient> getAllToppings();

    @RequestWrapper(localName = "createOrder", targetNamespace = "http://pizzatech", className = "pizzatech.test.CreateOrder")
    @WebMethod
    @ResponseWrapper(localName = "createOrderResponse", targetNamespace = "http://pizzatech", className = "pizzatech.test.CreateOrderResponse")
    public void createOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        pizzatech.test.Order arg0
    );
}
