
package pizzatech.dbaccess.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.6
 * Mon Apr 23 05:01:28 EEST 2012
 * Generated source version: 2.4.6
 */

@XmlRootElement(name = "addPizza", namespace = "http://pizzatech")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addPizza", namespace = "http://pizzatech")

public class AddPizza {

    @XmlElement(name = "arg0")
    private pizzatech.model.Pizza arg0;

    public pizzatech.model.Pizza getArg0() {
        return this.arg0;
    }

    public void setArg0(pizzatech.model.Pizza newArg0)  {
        this.arg0 = newArg0;
    }

}

